seed: 1380

model_name: Standard # or Standard|Wang2023Better_WRN-28-10

norm_thread: L2 # or Linf

dataset_name: cifar10

batch_size: 32 # put a value that gpu memory can bear

attack: fab #rreplace with 'autoattack' for auto-attack

results_root_path: . # a folder path to save the results

n_batches: 2